"""add fk usuario-telefono

Revision ID: 36437de253be
Revises: cb84fdb563b9
Create Date: 2025-06-11 09:20:32.438859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36437de253be'
down_revision: Union[str, None] = 'cb84fdb563b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telefonos', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telefonos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telefonos', type_='foreignkey')
    op.drop_column('telefonos', 'usuario_id')
    # ### end Alembic commands ###
