"""add telefono

Revision ID: 8938a40c855d
Revises: b5bedfa5fd67
Create Date: 2025-06-11 08:00:36.160355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8938a40c855d'
down_revision: Union[str, None] = 'b5bedfa5fd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('telefonos_ibfk_1'), 'telefonos', type_='foreignkey')
    op.drop_column('telefonos', 'usuario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telefonos', sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('telefonos_ibfk_1'), 'telefonos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###
