"""add cambios_usuario-usuario_genero

Revision ID: 93ec27e715b9
Revises: 36437de253be
Create Date: 2025-06-11 09:37:16.225920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93ec27e715b9'
down_revision: Union[str, None] = '36437de253be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios_generos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['generos_musicales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'genero_id')
    )
    op.add_column('generos_musicales', sa.Column('nombre', sa.String(length=50), nullable=True))
    op.drop_column('generos_musicales', 'tipo_genero')
    op.add_column('usuarios', sa.Column('documento', sa.Enum('CC', 'CE', 'TI', 'PASAPORTE', 'NIT', name='tipodocumento'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'documento')
    op.add_column('generos_musicales', sa.Column('tipo_genero', mysql.ENUM('ROCK', 'POP', 'JAZZ', 'CLASSICAL', 'HIP_HOP', 'COUNTRY', 'ELECTRONIC', 'REGGAE'), nullable=True))
    op.drop_column('generos_musicales', 'nombre')
    op.drop_table('usuarios_generos')
    # ### end Alembic commands ###
