"""add publicacion

Revision ID: 990d7a571d23
Revises: 6b7eb5459247
Create Date: 2025-06-11 11:00:03.969124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990d7a571d23'
down_revision: Union[str, None] = '6b7eb5459247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicaciones',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('reproducciones', sa.Integer(), nullable=True),
    sa.Column('vistas', sa.Integer(), nullable=True),
    sa.Column('tipo_de_publicacion', sa.String(length=80), nullable=True),
    sa.Column('nombre_del_archivo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicaciones')
    # ### end Alembic commands ###
