"""add usuario

Revision ID: af1ac5618702
Revises: bee517283265
Create Date: 2025-06-11 07:40:38.213214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1ac5618702'
down_revision: Union[str, None] = 'bee517283265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellidos', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('finalizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
