"""add tablas_faltantes

Revision ID: b974d74a6bff
Revises: 540a2a647564
Create Date: 2025-06-11 11:18:03.911053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b974d74a6bff'
down_revision: Union[str, None] = '540a2a647564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratista_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contratista_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['contratista_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('artista_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['artista_id'], ['artistas.usuario_id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postulados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacante_id', sa.Integer(), nullable=True),
    sa.Column('artista_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artista_id'], ['artistas.usuario_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postulados')
    op.drop_table('vacantes')
    op.drop_table('contratos')
    op.drop_table('contratista_categoria')
    op.drop_table('categorias')
    # ### end Alembic commands ###
