"""add genero_musical

Revision ID: cb84fdb563b9
Revises: 3fc2702b3b74
Create Date: 2025-06-11 09:07:49.206076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb84fdb563b9'
down_revision: Union[str, None] = '3fc2702b3b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generos_musicales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_genero', sa.Enum('ROCK', 'POP', 'JAZZ', 'CLASSICAL', 'HIP_HOP', 'COUNTRY', 'ELECTRONIC', 'REGGAE', name='tipogenero'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generos_musicales')
    # ### end Alembic commands ###
