"""add cancion-artista

Revision ID: dfd7895b9a6a
Revises: 4e81ba37f617
Create Date: 2025-06-11 11:06:13.113912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd7895b9a6a'
down_revision: Union[str, None] = '4e81ba37f617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('seguidores', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genero_id'], ['generos_musicales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('canciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('artista_id', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artista_id'], ['artistas.usuario_id'], ),
    sa.ForeignKeyConstraint(['genero_id'], ['generos_musicales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('canciones')
    op.drop_table('artistas')
    # ### end Alembic commands ###
