from .rol import Rol
from .usuario import Usuario
from .telefono import Telefono
from .genero_musical import GeneroMusical
from .usuario_genero import UsuarioGenero
from .publicacion import Publicacion
from .contratista import Contratista
from .cancion import Cancion
from .artista import Artista
from .espectador import Espectador
from .competencia import Competencia
from .contrato import Contrato
from .vacante import Vacante
from .postulado import Postulado
from .categoria import Categoria
from .contratistaCategoria import ContratistaCategoria